version: 2

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1

    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-rd-client-lib
      - run:
          name: Compile
          command: dotnet build --packages .packages
      - run:
          name: Unit Tests
          command: |
            dotnet test -v normal --logger "trx" --no-restore --no-build --collect:"XPlat Code Coverage"
      - run:
          name: Convert test trx files to JUnit
          command: dotnet tool install -g trx2junit || true && ~/.dotnet/tools/trx2junit RentDynamics.RdClient.Tests/TestResults/*.trx --output test-results
          when: always
      - store_test_results:
          path: test-results
          when: always
      - run:
          name: Upload Code coverage results
          command: |
            initial_covfile=$(find . -name "coverage.cobertura.xml")
            initial_covfiles_count=$(echo "$initial_covfile" | wc -l)
            echo "Found 'initial_covfiles_count' initial coverage files"
            
            dotnet tool install -g codecov.tool || true
            
            covfile=$(find . -name "coverage.cobertura.xml" | head -1)
            covfiles_count=$(echo "$covfile" | wc -l)
            echo "Found '$covfiles_count' coverage files"
            echo "Cov file path: $covfile"
            
            ~/.dotnet/tools/codecov -f "$covfile"
          when: always
      - save_cache:
          key: dotnet-rd-client-lib
          paths:
            - .packages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: DotNetBuild    